version: "3"

services:
  exporter:
    image: iout1aw/mikrotik-exporter:master
    container_name: mikrotik-exporter
    restart: unless-stopped
    volumes:
      - ./config.yml:/app/config.yml
    environment:
      - CONFIG_FILE=/app/config.yml
    ports:
      - 9436:9436
