version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14-stretch
    branches:
      only:
        - master
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run: make dockerhub
