name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13.8
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Define variables
        run: |
          echo ".version" > VERSION_FILE
          cat $(cat VERSION_FILE) | grep VERSION= | head -n 1 | grep -o '".*"' | sed 's/"//g' > VERSION

      - name: Set SHORTSHA
        id: sha
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build
        env:
          LDFLAGS: "-X main.appVersion=$(cat VERSION) -X main.shortSha=${{ steps.sha.outputs.sha_short }}"
        run: go build -v -ldflags ${LDFLAGS} .
